---
daylily:
  git_tag: 0.7.196t
  git_repo: https://github.com/Daylily-Informatics/daylily.git
  git_repo_ssh: git@github.com:Daylily-Informatics/daylily.git
  analysis_root: /fsx/analysis_results/
  daylily_image_cmd: "singularity pull --name /fsx/resources/environments/containers/daylily:0.7.196.simg docker://daylilyinformatics/daylily:0.7.196"
  daylily_image_path: /fsx/resources/environments/containers/daylily:0.7.196.simg
  sentieon_lic_path: /fsx/data/cached_envs/Life_Sciences_Manufacturing_Corporation_eval.lic
  sentieon_tmpdir: /dev/shm/
  sentieon_install_dir: /fsx/data/cached_envs/sentieon-genomics-202503.01.rc1/