name: base
channels:
  - r
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.3.1=py39hf3d152e_0
  - conda-content-trust=0.1.3=py39h06a4308_0
  - conda-package-handling=2.0.2=py39h06a4308_0
  - conda-package-streaming=0.7.0=py39h06a4308_0
  - cryptography=38.0.4=py39h9ce1e76_0
  - fmt=9.1.0=h924138e_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=py39h06a4308_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h3d51595_0
  - libcurl=7.88.1=hdc1c0ab_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libsolv=0.7.23=h3eb15da_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libxml2=2.10.3=hfdac1af_6
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.0=h417c0b6_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - ncurses=6.4=h6a678d5_0
  - openssl=3.1.0=h0b41bf4_0
  - packaging=23.0=pyhd8ed1ab_0
  - pip=22.3.1=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.4=py39h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h2782a2a_0_cpython
  - python_abi=3.9=3_cp39
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.28.1=py39h06a4308_0
  - ruamel.yaml=0.17.21=py39h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py39h06a4308_0
  - tqdm=4.64.1=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - yaml-cpp=0.7.0=h27087fc_2
  - zlib=1.2.13=h166bdaf_4
  - zstandard=0.18.0=py39h5eee18b_0
  - zstd=1.5.2=h3eb15da_6
prefix: /home/jmajor/miniconda3
