---
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas==1.5.3
  - python==3.11.11
  - ipython
  - perl
  - yappi
  - networkx
  - yamllint
  - pip
  - rclone
  - parallel
  - pygraphviz
  - glances
  - tabix
  - fd-find
  - graphviz
  - nodejs
  - jq
  - yq
  - pip:
    - docopt==0.6.2
    - colr==0.9.1
    - xmltodict
    - wrapt
    - tabulate
    - ruamel.yaml
    - aws-parallelcluster==3.11.1
