---
supporting_files:   ## All of this structure was for an exploratory, now deprecated , system that let you declare resources from mixed sources.  It's simply paths now :-)  And if not leading with a '/', then is relative to the snakemake working dir.
  root: /fsx/data/
  files:
    huref:
      ref:
        class: file_no_suffix_star          # This is for use with local copy and webdav copy. These dirs contain other share resources that don't need to be dragged around unecessarily
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.fasta
      genome_file:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.genome
      fasta:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.fasta
        bed: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.bed
      bed:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.bed
      female_diploid:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37
      female_haploid:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37
      male_diploid:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37
      male_haploid:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37
      core_bed:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/blah/b37_broad_core.bed
      hisat2:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37
      bwa_mem_sent:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.fasta.gz
      bwa_mem_index_vanilla:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.fasta.gz
      bwa_mem_index_fast:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/bwa-mem2b/human_1kg_v37.fasta.gz
      bwa_mem_index_meme:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/bwa_mem2_meme/human_1kg_v37.fasta
      bwa_mem_index_meme_b:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/bwa_mem2_meme_b/human_1kg_v37.fasta
      bwa_mem2_scale:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/bwa_mem2_scale/human_1kg_v37.fasta
      rtg_tools_genome:
        class: dir_plus
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.fasta.gz.sdf/
      truth_data:
        class: dir_plus
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/controls/b37/controls/
      giab_na12878_hc_snv_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/controls/b37/controls/NA12878/giab/NA12878.bed
      calling_regions:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/calling_regions.bed
      svaba_calling_regions:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/svaba_calling_regions.bed
    vep:
      vep_genome_build: 113_GRCh37
      vep_cache:
        class: file_only
        name: /fsx/data/tool_specific_data/vep/
    snpeff:
      ref_build_code: GRCh37.75
    ucsc:
      simple_repeats_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/b37_ucsc_simple_repeats.bed
      problem_regions_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/ucsc_hg19_ucscfilter_track.bed
      dbsnp152:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/b37_dbsnp152_bed.bed
      build_gaps:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/ucsc_hg19_ucscfilter_track.bed
      encode_blacklist:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/b37_ucsc_encode_blacklist.bed
      seg_dups:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/b37_ucsc_seqdup_bed
      genomeincidents:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/b37_genomeincidents.bed
      mappability_k23:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/ucsc_23mapabilitty.bed
      gc_5bpwin:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/ucsc_b37_gc5bpwin.bed
      dac_blacklist:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/table_browser_track_beds/ucsc_DAC_Blacklist.bed.bed
    dbsnp:
      broad_snowman_indelvcf:
        class: file_only
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/svaba/dbsnp_indel.vcf
    contam:
      ref_vcf:
        class: file_only
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/supersonic_modules/RE2666_intersect_1000g_phase1_release_v3.20101123.vcf
    iddnas:
      human_iddnas:
        class: file_only
        name: /fsx/data/internal_assay_data/H_sapiens/b37/IDDNAS_ALL/only_human_iddnas_ultraplex_2021_09_29.tsv
      alien_iddnas:
        class: file_only
        name: /fsx/data/internal_assay_data/H_sapiens/b37/IDDNAS_ALL/only_alien_iddnas_ultraplex_2021_09_29.tsv
      both_human_alien:
        class: file_only
        name: /fsx/data/internal_assay_data/H_sapiens/b37/IDDNAS_ALL/both_human_alien_iddnas_ultraplex_2021_09_29.tsv
    verifybam2:
      dat_files:
        class: file_no_suffix_star
        name:  /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/snp_vcfs/chr20_verbam/chr20.sampled.vcf.gz
      oneM_snps_vcf:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/snp_vcfs/chr20_verbam/chr20.sampled.vcf.gz
      oneM_snps_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/snp_vcfs/chr20_verbam/chr20.sampled.vcf.gz
    fastv:
      microbial_kmer_collection:
        class: file_only
        name: /fsx/data/tool_specific_resources/fastv/microbial.kc.fasta.gz
      influenza_kmer_collection:
        class: file_only
        name: /fsx/data/tool_specific_resources/fastv/influenzaA.kc.fasta.gz
      covid_kmer:
        class: file_only
        name: /fsx/data/tool_specific_resources/fastv/SARS-CoV-2.kmer.fa
      covid_genomes:
        class: file_only
        name: resopuirces/fsx/data/tool_specific_resources/fastv/SARS-CoV-2.genomes.fa
    glimpse:
      GLIMPSE_huref:
        class: file_so_suffix_start
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.fasta
      GLIMPSE_noNA12878_sites:
        class: file_only
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/GLIMPSE/references/b37/reference_panel/1000GP.0.noNA12878.sites.wGT.vcf.gz
    somalier:
      genome_sites:
        class: file_only
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/somalier/sites_files/sites.GRCh37.vcf.gz
    octopus:
      huref:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/human_1kg_v37/human_1kg_v37.fasta
      forest_model_a:
        class: file_only
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/octopus/forests/germline.v0.7.4.forest
      error_model:
        class: file_only
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/octopus/octopus_err_models/novaseq.4a38e55.model
      skip_regions_f:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/b37/ucsc/ucsc_hg19_ucscfilter_track.bed
    microbial:
      reprDB:  # https://pubmed.ncbi.nlm.nih.gov/29347966/
        class: file_only
        name: /fsx/data/genomic_data/organism_references/microbial/PanGenome/PanGenome/reprDB.fasta
      panDB:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/microbial/PanGenome/PanGenome/panDB.fasta
        # https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0399-2
        # https://github.com/ohlab/panDB
    giab_sv:
      v0.6_NA24385_ties_1_2:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/b37/controls/b37/controls/cnv/NA24385/giab-0.6/HG002_SVs_Tier1plusTier2_v0.6.1.bed
    sentieon:
      dnascope_model:
        class: file_only
        name: resources/sentieon/SentieonDNAscopeModel1.1.model