---
supporting_files:   ## All of this structure was for an exploratory, now deprecated , system that let you declare resources from mixed sources.  It's simply paths now :-)  And if not leading with a '/', then is relative to the snakemake working dir.
  root: /fsx/data/
  files:
    huref:
      ref:
        class: file_no_suffix_star          # This is for use with local copy and webdav copy. These dirs contain other share resources that don't need to be dragged around unecessarily
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      genome_file:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      fasta_orig:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      bed:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_broad.bed
      female_diploid:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_diploid_female.bed
      female_haploid:
        class: file_no_suffix_star
        name: ""
      male_diploid:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_diploid_male.bed
      male_haploid:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_haploid_male.bed
      core_bed:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_broad_core.bed
      fasta:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
        bed: /fsx/data/genomic_data/organism_references/H_sapiens/hg38_broad/hg38_broad_core.bed
      fasta_minalt:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      hisat2:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      bwa_sent:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      bwa_mem_index_vanilla:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      bwa_mem_index_fast:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      bwa_mem_sent:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      bwa_mem_index_meme:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      rtg_tools_genome_full:
        class: dir_plus
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/rtg/Homo_sapiens_assembly38.fasta.sdf
      rtg_tools_genome_noalt:
        class: dir_plus
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta.sdf
      rtg_tools_genome:
        class: dir_plus
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta.sdf
      truth_data:
        class: dir_plus
        name: /fsx/data/genomic_data/organism_annotations/createme.note
      giab_na12878_hc_snv_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      calling_regions:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      svaba_calling_regions:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
    vep:
      vep_genome_build: 113_GRCh38
      vep_cache:
        class: file_only
        name: /fsx/data/tool_specific_data/vep/
    snpeff:
      ref_build_code: GRCh38.99
    ucsc:
      simple_repeats_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/ucsc/ucsc_hg38_simple_repeats.bed
      problem_regions_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      dbsnp152:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/ncbi/dbsnp/GCF_000001405.40.vcf.gz.tbi/GCF_000001405.40.vcf.gz
      build_gaps:
        class: file_only
        name: resources/grch38_ucsc_gaps.bed 
      encode_blacklist:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      seg_dups:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      genomeincidents:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      mappability_k23:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      gc_5bpwin:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      dac_blacklist:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
    dbsnp:
      broad_snowman_indelvcf:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/ncbi/dbsnp/GCF_000001405.40.vcf.gz.tbi/GCF_000001405.40.vcf.gz
    contam:
      ref_vcf:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
    iddnas:
      human_iddnas:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      alien_iddnas:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      both_human_alien:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
    verifybam2:
      dat_files:
        class: file_no_suffix_star
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/snp_vcfs/snp_subset_1M/filtered_vcfs/merged.500perchr.nosamp.sort.vcf.gz 
      oneM_snps_vcf:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/snp_vcfs/snp_subset_1M/filtered_vcfs/merged.500perchr.nosamp.sort.vcf.gz
      oneM_snps_bed:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/snp_vcfs/snp_subset_1M/filtered_vcfs/merged.500perchr.nosamp.sort.vcf.gz
    fastv:
      microbial_kmer_collection:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      influenza_kmer_collection:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      covid_kmer:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      covid_genomes:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
    glimpse:
      GLIMPSE_huref:
        class: file_so_suffix_start
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      GLIMPSE_noNA12878_sites:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
    somalier:
      genome_sites:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
    octopus:
      huref:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/fasta_fai_minalt/GRCh38_no_alt_analysis_set.fasta
      forest_model_a:
        class: file_only
        name: /fsx/data/tool_specific_resources/H_sapiens/b37/octopus/forests/germline.v0.7.4.forest
      skip_regions_f:
        class: file_only
        name: resources/grch38_ucsc_gaps.bed 
    microbial:
      reprDB:  # https://pubmed.ncbi.nlm.nih.gov/29347966/
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
      panDB:
        class: file_only
        name: /fsx/data/genomic_data/organism_references/H_sapiens/hg38/blah.createme.note
        # https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0399-2
        # https://github.com/ohlab/panDB
    giab_sv:
      v0.6_NA24385_ties_1_2:
        class: file_only
        name: /fsx/data/genomic_data/organism_annotations/H_sapiens/hg38/controls/giab/snv/v4.2.1/HG001/giabHC/HG001.bed
    sentieon:
      dnascope_model:
        class: file_only
        name: resources/sentieon/SentieonDNAscopeModel1.1.model
 
